replicaCount: 1

image:
  repository: selvoc-keycloak
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  host: keycloak.selvoc.local
  annotations: {}

resources:
  requests:
    memory: "600Mi"
    cpu: "100m"
  limits:
    memory: "1.5Gi"
    cpu: "1"

auth:
  username: admin
  password: "" # Set this to a secure password (for example, from github secrets)

env:
  KC_DB: postgres
  KC_DB_URL_PORT: 5432
  KC_DB_URL_DATABASE: keycloak
  KC_HEALTH_ENABLED: true
  KC_METRICS_ENABLED: true
  KC_HTTP_RELATIVE_PATH: /
  KK_TO_RMQ_PORT: 5672
  KK_TO_RMQ_VHOST: /
  KK_TO_RMQ_EXCHANGE: keycloak.topic

secrets:
  external:
    enabled: false
    refreshInterval: 1h
    data:
      KC_DB_URL_HOST:
        key: postgres
        property: host
      KC_DB_USERNAME:
        key: postgres
        property: username
      KC_DB_PASSWORD:
        key: postgres
        property: password

      KK_TO_RMQ_URL:
        key: rabbitmq
        property: host
      KK_TO_RMQ_USERNAME:
        key: rabbitmq
        property: username
      KK_TO_RMQ_PASSWORD:
        key: rabbitmq
        property: password
