replicaCount: 1

image:
  repository: bobo-keycloak
  tag: latest
  pullPolicy: Never  # Local dev

service:
  type: ClusterIP
  port: 5555

ingress:
  enabled: true
  hosts:
    - host: keycloak.bobo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: "600Mi"
    cpu: "100m"
  limits:
    memory: "1.5Gi"
    cpu: "1"

env:
  - name: KC_DB
    value: "postgres"
  - name: KC_DB_URL_HOST
    value: "postgres.bobo.svc.cluster.local"
  - name: KC_DB_URL_PORT
    value: "5432"
  - name: KC_DB_URL_DATABASE
    value: "keycloak"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/"
  - name: KC_HTTP_PORT
    value: "5555"
  - name: KK_TO_RMQ_URL
    value: "rabbitmq.bobo.svc.cluster.local"
  - name: KK_TO_RMQ_PORT
    value: "5672"
  - name: KK_TO_RMQ_VHOST
    value: "/"
  - name: KK_TO_RMQ_EXCHANGE
    value: "keycloak.topic"

# Temp
secrets:
  adminUsername: admin
  adminPassword: admin
  postgresUsername: postgres
  postgresPassword: postgres
  rabbitmqUsername: guest
  rabbitmqPassword: guest
