services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USERNAME:-postgres}' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./configs/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  keycloak:
    build: configs/keycloak
    restart: unless-stopped
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    environment:
      # https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USERNAME:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: ${POSTGRES_PORT:-5432}
      KC_DB_URL_DATABASE: keycloak
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /
      # Provider: https://github.com/aznamier/keycloak-event-listener-rabbitmq
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: ${RABBITMQ_PORT:-5672}
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: ${KEYCLOAK_RABBITMQ_EXCHANGE:-keycloak.topic}
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
    command: start-dev --import-realm
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # Services

  gateway-service:
    build:
      context: .
      dockerfile: backend/gateway/Dockerfile
      secrets:
        - github_token
    restart: unless-stopped
    ports:
      - ${GATEWAY_PORT:-3000}:3000
    environment:
      SUBGRAPH_USER_URL: http://user-service:3000/graphql
      SUBGRAPH_CHAT_URL: http://chat-service:3000/graphql
      LOGGER_LEVEL: debug
      HOSTNAME: '::'
    depends_on:
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: backend/user/Dockerfile
      secrets:
        - github_token
    restart: unless-stopped
    ports:
      - ${USER_PORT:-3001}:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: user
      POSTGRES_POOL_SIZE: 10
      KEYCLOAK_BASE_URL: http://keycloak:${KEYCLOAK_PORT:-8080}
      KEYCLOAK_REALM: selvoc
      KEYCLOAK_CLIENT_ID: ${USER_KEYCLOAK_CLIENT_ID:-user-service}
      KEYCLOAK_CLIENT_SECRET: $USER_KEYCLOAK_CLIENT_SECRET
      RABBITMQ_PROTOCOL: amqp
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      LOGGER_LEVEL: debug
      HOSTNAME: '::'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  chat-service:
    build:
      context: .
      dockerfile: backend/chat/Dockerfile
      secrets:
        - github_token
    restart: unless-stopped
    ports:
      - ${CHAT_PORT:-3002}:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: chat
      POSTGRES_POOL_SIZE: 10
      KEYCLOAK_BASE_URL: http://keycloak:${KEYCLOAK_PORT:-8080}
      KEYCLOAK_REALM: selvoc
      KEYCLOAK_CLIENT_ID: ${CHAT_KEYCLOAK_CLIENT_ID:-chat-service}
      KEYCLOAK_CLIENT_SECRET: $CHAT_KEYCLOAK_CLIENT_SECRET
      RABBITMQ_PROTOCOL: amqp
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      LOGGER_LEVEL: debug
      HOSTNAME: '::'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

secrets:
  github_token:
    environment: GITHUB_TOKEN

volumes:
  postgres_data:
  rabbitmq_data:
