apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobo-backend
  namespace: bobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobo-backend
  template:
    metadata:
      labels:
        app: bobo-backend
    spec:
      containers:
        - name: bobo-backend
          image: bobo-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: port

            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: postgres-password

            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: postgres-database

            - name: POSTGRES_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: postgres-pool-size

            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: base-url

            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: realm

            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: keycloak-client-id

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: backend-keycloak-client-secret

            - name: AMQP_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: protocol

            - name: AMQP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: host

            - name: AMQP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: rabbitmq-username

            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: rabbitmq-password

            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: port

            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: logger-level

          readinessProbe:
            tcpSocket: # TODO: add /health endpoint
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bobo-backend
  namespace: bobo
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: bobo-backend
