apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bobo-ingress
  namespace: bobo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.bobo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bobo-backend
            port:
              number: 3000

  - host: keycloak.bobo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 5555

  - host: rabbitmq.bobo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
