apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: bobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bobo-keycloak:latest
          imagePullPolicy: Never
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev", "--import-realm", "--health-enabled=true"]
          ports:
            - containerPort: 5555
            - containerPort: 9000
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: keycloak-admin-password
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_USERNAME
              value: "postgres"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: postgres-password
            - name: KC_DB_URL_HOST
              value: "postgres.bobo.svc.cluster.local"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/"
            - name: KC_HTTP_PORT
              value: "5555"
            - name: KK_TO_RMQ_URL
              value: "rabbitmq.bobo.svc.cluster.local"
            - name: KK_TO_RMQ_PORT
              value: "5672"
            - name: KK_TO_RMQ_VHOST
              value: "/"
            - name: KK_TO_RMQ_EXCHANGE
              value: "keycloak.topic"
            - name: KK_TO_RMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: rabbitmq-username
            - name: KK_TO_RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bobo-secrets
                  key: rabbitmq-password
          readinessProbe:
            tcpSocket: # TODO: make health check
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: bobo
spec:
  ports:
    - port: 5555
      targetPort: 5555
      name: api
    - port: 9000
      targetPort: 9000
      name: health
  selector:
    app: keycloak
