apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.auth.username | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.auth.password | b64enc }}
