export const CHAT_REPOSITORY_TOKEN = Symbol('CHAT_REPOSITORY_TOKEN');
export const CHAT_MEMBER_REPOSITORY_TOKEN = Symbol('CHAT_MEMBER_REPOSITORY_TOKEN');
export const CHAT_MESSAGE_REPOSITORY_TOKEN = Symbol('CHAT_MESSAGE_REPOSITORY_TOKEN');
