replicaCount: 1

image:
  repository: selvoc-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  host: gateway.selvoc.local
  annotations: {}

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  SUBGRAPH_USER_URL: http://user.selvoc.svc.cluster.local:3000/graphql
  SUBGRAPH_CHAT_URL: http://chat.selvoc.svc.cluster.local:3000/graphql

  LOGGER_LEVEL: debug

secrets:
  external:
    enabled: false
