apiVersion: v1
kind: Pod
metadata:
  name: postgres-proxy
spec:
  containers:
  - name: socat
    image: alpine/socat
    command: ["socat", "TCP-LISTEN:5432,fork", "TCP:postgres:5432"]
# kubectl -n bobo-dev port-forward pod/postgres-proxy 5432:5432
