apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresUsername: {{ .Values.secrets.postgresUsername | b64enc }}
  postgresPassword: {{ .Values.secrets.postgresPassword | b64enc }}
  keycloakClientSecret: {{ .Values.secrets.keycloakClientSecret | b64enc }}
  rabbitmqUsername: {{ .Values.secrets.rabbitmqUsername | b64enc }}
  rabbitmqPassword: {{ .Values.secrets.rabbitmqPassword | b64enc }}
