apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  keycloakClientSecret: {{ .Values.secrets.keycloakClientSecret | b64enc }}
