{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $value := .Values.secrets.external.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value.key }}
        property: {{ $value.property }}
    {{- end }}
{{- end }}
