# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 17.4.0-debian-12-r14

architecture: standalone

fullnameOverride: postgres

auth:
  username: "postgres"
  existingSecret: "postgres-secrets"
  secretKeys:
    adminPasswordKey: "adminPassword"

primary:
  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "300m"

  extraEnvVars:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secrets
          key: adminPassword
    - name: KEYCLOAK_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres-secrets
          key: keycloakUsername
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secrets
          key: keycloakPassword

  initdb:
    scripts:
      init.sh: |
        #!/bin/bash
        set -e

        # Set PGPASSWORD to the postgres user's password
        export PGPASSWORD=$POSTGRES_PASSWORD

        # Escape single quotes in the password for SQL safety
        ESCAPED_KEYCLOAK_PASSWORD=$(echo "$KEYCLOAK_PASSWORD" | sed "s/'/''/g")

        psql -U postgres -d postgres -c "CREATE USER $KEYCLOAK_USERNAME WITH ENCRYPTED PASSWORD '$ESCAPED_KEYCLOAK_PASSWORD';"
        psql -U postgres -d postgres -c "CREATE DATABASE keycloak;"
        psql -U postgres -d postgres -c "GRANT ALL ON DATABASE keycloak TO keycloak;"
        psql -U postgres -d keycloak -c "GRANT USAGE, CREATE ON SCHEMA public TO keycloak;"
        psql -U postgres -d postgres -c "CREATE DATABASE \"user\";"
        psql -U postgres -d postgres -c "CREATE DATABASE \"chat\";"
        psql -U postgres -d postgres -c "CREATE DATABASE \"vocabulary\";"
