# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 17.4.0-debian-12-r14

architecture: standalone

fullnameOverride: postgres

auth:
  username: "postgres"
  existingSecret: "postgres-secrets"
  secretKeys:
    adminPasswordKey: "adminPassword"

primary:
  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "300m"

  initdb:
    scripts:
    # TODO: properly insert secrets
      init.sql: |
        -- keycloak
        CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';
        CREATE DATABASE keycloak;
        GRANT ALL ON DATABASE keycloak TO keycloak;
        \c keycloak
        GRANT USAGE, CREATE ON SCHEMA public TO keycloak;

        -- databases for services
        CREATE DATABASE "user";
        CREATE DATABASE "chat";
        CREATE DATABASE "vocabulary";
