apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  adminUsername: {{ .Values.secrets.adminUsername | b64enc }}
  adminPassword: {{ .Values.secrets.adminPassword | b64enc }}
