name: CI/CD for Chat
on:
  push:
    branches:
      - main
    paths:
      - 'backend/chat/**'
      - 'infrastructure/helm/chat/**'
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      name: chat
      context: .
      dockerfile: backend/chat/Dockerfile
      helm_values_file: dev.values.yaml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
      K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
